version: '3'
services:
  database:
    build: ./bd
  frontend:
    build: ./front
    ports:
      - "80:80"
  backend:
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - database
  
volumes:
  database-data: