version: '3'
services:
  frontend:
    build: ./front
    ports:
      - "5173:5173"
  backend:
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    build: ./bd
volumes:
  database-data: